### ISSUE TITLE
New Feature: Only analyze crates that users upload.

### ISSUE THREAD

**Issue by xizheyin** [crates-pro/crates-pro#67]
Yesterday, we discussed with Mr. Feng that since analyzing all versions of all repositories consumes a lot of computing resources, we don't need to analyze all the repositories in the corpus, but only the repositories uploaded by users and their dependencies. This can be realized with only a few changes. But now there are the following problems:
1. Do we need enough information if we want to implement the recommendation function. Do we need to analyze the latest version of each repository?
2. If we follow this scenario, there is only one type of analysis left to perform on all repositories, which is the dependency propagation of CVEs, is this too little again?

**Comment by xizheyin** [comment]
The crates on crates.io may be in line with the “2-8 law”, that is, 20% of crates cover 80% of application scenarios.

We can first include the latest version of the top 1000 crates in the recommended scope and analyze it, and then analyze it on demand (add crates that are relied on by the crates uploaded by users but are not included in the recommended scope to the recommended scope).  Said by @duinomaker .

**Comment by xizheyin** [comment]
It's a good idea

**Comment by xizheyin** [comment]
The front-end needs to write the corresponding message under the kafka topic KAFKA_USER_IMPORT_TOPIC=“USER_UPLOAD” for the back-end to parse.

**Comment by xizheyin** [comment]
How does kafka communicate between the front end and the back end? Assuming they are not on the same server, is it possible to write directly through the backend ip. @duinomaker

**Comment by martinwq997** [comment]
1!!!

**Comment by duinomaker** [comment]
> How does kafka communicate between the front end and the back end?

Kafka doesn't communicate between the frontend and the backend, it's a backend-only component. I've reviewed [cratespro-frontend](https://github.com/crates-pro/cratespro-frontend), and if I understand correctly, currently only the Node.js service is in between the frontend and the rest of the Crates Pro deployment. Can you confirm this, @genedna @benjamin-747 ?

I've drawn a diagram illustrating user interaction with Crates Pro, showing Kafka's position and the process when a user requests a web page:

![User requests a web page](https://github.com/user-attachments/assets/6529186a-be03-4261-be82-821ef3f9c358)

1. Node.js service retrieves data from PostgreSQL
2. Node.js runs Next.js to render the requested web page
3. Node.js sends the rendered web page to the user
4. User views the page in their browser

> Assuming they are not on the same server, is it possible to write directly through the backend ip

The HTTP service provided by the Node.js server is currently the only service users have access to. They should send their crate to the Node.js service via HTTP. The Node.js service then puts that crate into Kafka as a message. Here's a diagram for this workflow:

![User uploads a crate](https://github.com/user-attachments/assets/97b4c83e-e1b4-4b60-bbaa-124793729a3d)

1. User uploads (via HTTP request)
2. Node.js service processes the crate as a Kafka message and puts it into the "USER_UPLOAD" topic

**Comment by benjamin-747** [comment]
> The HTTP service provided by the Node.js server is currently the only service users have access to. They should send their crate to the Node.js service via HTTP.

We use a Node.js service to host Nextjs frontend pages and perform [server-side rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components). The only remaining question is whether database and Kafka operations should be handled by the Node.js service or by `cratespro`. Normally, these operations should be handled by the `cratespro` backend, with corresponding APIs provided for the Node.js service to use.

**Comment by benjamin-747** [comment]
@xizheyin I discussed with @genedna , and we concluded that cratespro needs to provide APIs for database operations (such as data display on the front-end). These APIs can also be shared with other services in the future.

**Comment by xizheyin** [comment]
I understand that it's about hiding details from the front end. On the one hand, the operation of reading out the data doesn't need to be done via pg; on the other hand, the operation of depositing into the uploaded repository is done by crates-pro. They both operate through the api for http provided by crates-pro. @benjamin-747

**Comment by xizheyin** [comment]
@martinwq997 
After I provide the apis for the front-end, you can modify the front-end to read and write data.

**Comment by xizheyin** [comment]
I have exposed the restful service at `6888`. How the front end connect with it (which port)? @duinomaker @martinwq997 
API Endpoints
`GET /api/crates`: Retrieve information about all crates.
`GET /api/crates/{name}`: Retrieve details about a specific crate.

**Comment by xizheyin** [comment]
I have a new question, where should I store these repositories when crates-pro download crates from mega or get crates from users? This part is actually quite large in quantity, so do I need to open a separate docker to open an additional filesystem. Otherwise, crates-pro the container will be huge. @genedna @benjamin-747 @duinomaker

**Comment by 201220158** [comment]
good

**Comment by xizheyin** [comment]
This feature will be complished by @201220158 (backend) and @martinwq997 (frontend).
